<div class="right-data">
<div class="top-info"><!-- today-monitor-->
<table cellpadding="0" cellspacing="0" border="0" width="100%">
	<tr>
		<td>今日监测：</td>
		<td>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		<p>IP:260万、日环比5%；周同比3%、月同比2%、年同比20%；年初定比增长15%</p>
		</td>
	</tr>
</table>
<!-- today-monitor end--></div>

<!-- search  -->
<div class="search-box">
<table cellpadding="0" cellspacing="0" border="1" width="100%">
	<tr>
		<td><select>
			<option>北京大区</option>
			<option>上海大区</option>
		</select></td>
		<td><select>
			<option>海淀</option>
			<option>朝阳</option>
		</select></td>
		<td><input type="radio" name="" />按天查询</td>
		<td><input type="radio" name="" />按周查询</td>
		<td><input type="radio" name="" />按月查询</td>
		<td>Begintime <select>
			<option>2011-06</option>
			<option>2011-7</option>
		</select></td>
		<td>Endtime <select>
			<option>2011-06</option>
			<option>2011-7</option>
		</select></td>
		<td><a class="search-btn"><cite>查询</cite></a></td>
	</tr>
</table>
</div>
<!-- search end  --> <!-- table -->
<div class="table-data-box">
<table cellpadding="0" cellspacing="0" class="data-header">
	<tr>
		<td>城市</td>
		<td>城市</td>
		<td>城市</td>
		<td>城市</td>
		<td>城市</td>
		<td>城市</td>
	</tr>
</table>
<div class="data-body">
<table cellpadding="0" cellspacing="0" width="100%" class="data-body">
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
	<tr>
		<td>城市</td>
		<td>PV</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
		<td>量子</td>
	</tr>
</table>
</div>


</div>
<!-- table end --></div>